//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LEVEL_SELECTED = 'LEVEL_SELECTED';
export const VOCAB_LESSON_SELECTED = 'VOCAB_LESSON_SELECTED';
export const CHUHAN_LESSON_SELECTED = 'CHUHAN_LESSON_SELECTED';
export const LISTENING_LESSON_SELECTED = 'LISTENING_LESSON_SELECTED';
export const DIALOG_LESSON_SELECTED = 'DIALOG_LESSON_SELECTED';
export const READING_LESSON_SELECTED = 'READING_LESSON_SELECTED';
export const SUB_TEST_SELECTED = 'SUB_TEST_SELECTED';
