export const DATA = [
  {
    id: 1,
    name: 'Văn Đức sensei',
    sex: 'M',
    date: '04/03/2020',
    startTime: '10:30 AM',
    endTime: '10:30 AM',
    tags: ['Từ vựng', 'N1', 'N2', 'N3', 'N4', 'N5'],
    avatar: 'https://nihong0.herokuapp.com/avatars/admin.jpg',
    program: 'Học từ vựng theo chủ đề',
    description: 'Cùng học từ vựng theo chủ đề với Văn Đức sensei',
    available: true,
  },
  {
    id: 2,
    name: 'Văn Đức sensei',
    sex: 'M',
    date: '04/03/2020',
    startTime: '11:00 AM',
    endTime: '12:00 AM',
    tags: ['Ngữ pháp', 'Luyện mỗi ngày'],
    avatar: 'https://nihong0.herokuapp.com/avatars/admin.jpg',
    program: 'Ngữ pháp',
    description: 'Cùng Văn Đức sensei học ngữ pháp',
    available: false,
  },
  {
    id: 3,
    name: 'Văn Đức sensei',
    sex: 'M',
    date: '05/03/2020',
    startTime: '9:00 AM',
    endTime: '10:00 AM',
    tags: ['Nghe', 'Luyện mỗi ngày'],
    avatar: 'https://nihong0.herokuapp.com/avatars/admin.jpg',
    program: 'Luyện nghe',
    description: 'Cùng luyện nghe với Văn Đức sensei mỗi ngày',
    available: false,
  },
  {
    id: 4,
    name: 'Văn Đức sensei',
    sex: 'M',
    date: '05/03/2020',
    startTime: '11:00 AM',
    endTime: '13:00 AM',
    tags: ['Nói', 'Luyện mỗi ngày'],
    avatar: 'https://nihong0.herokuapp.com/avatars/admin.jpg',
    program: 'Luyện nói',
    description: 'Luyện nói cùng với Văn Đức sensei',
    available: false,
  },

  {
    id: 5,
    name: 'Văn Đức sensei',
    sex: 'M',
    date: '05/03/2020',
    startTime: '10:30 AM',
    endTime: '10:30 AM',
    tags: ['Viết', 'Luyện mỗi ngày'],
    avatar: 'https://nihong0.herokuapp.com/avatars/admin.jpg',
    program: 'Luyện viết',
    description: 'Tập viết mỗi ngày cùng với Văn Đức sensei',
    available: false,
  },
  {
    id: 6,
    name: 'Văn Đức sensei',
    sex: 'M',
    date: '05/03/2020',
    startTime: '11:00 AM',
    endTime: '12:00 AM',
    tags: ['Luyện thi', 'HOT'],
    avatar: 'https://nihong0.herokuapp.com/avatars/admin.jpg',
    program: 'Luyện thi',
    description: 'Thực hành các bài thi N1-N5 với Văn Đức sensei',
    available: false,
  },
  //   ],
  // },
];
