export const PROGRAM_IDS = {
  TUVUNG: 1,
  CHUHAN: 2,
  NGHE: 3,
  HOITHOAI: 4,
  // THI: 6,
};

export const DATA = [
  {
    id: PROGRAM_IDS.TUVUNG,
    name: 'Văn Đức sensei',
    sex: 'M',
    date: '04/03/2020',
    startTime: '10:30 AM',
    endTime: '10:30 AM',
    tags: ['N5', 'N4', 'N3', 'N2', 'N1'],
    avatar: 'https://nihong0.herokuapp.com/avatars/logo.jpg',
    program: 'Từ vựng',
    description: 'Học theo cấp độ',
    available: true,
  },
  {
    id: PROGRAM_IDS.CHUHAN,
    name: 'Văn Đức sensei',
    sex: 'M',
    date: '05/03/2020',
    startTime: '11:00 AM',
    endTime: '13:00 AM',
    tags: ['N5', 'N4', 'N3', 'N2', 'N1'],
    avatar: 'https://nihong0.herokuapp.com/avatars/logo.jpg',
    program: 'Chữ Hán',
    description: 'Học theo cấp độ',
    available: true,
  },
  // {
  //   id: PROGRAM_IDS.NGUPHAP,
  //   name: 'Văn Đức sensei',
  //   sex: 'M',
  //   date: '04/03/2020',
  //   startTime: '11:00 AM',
  //   endTime: '12:00 AM',
  //   tags: ['N5', 'N4', 'N3', 'N2', 'N1'],
  //   avatar: 'https://nihong0.herokuapp.com/avatars/logo.jpg',
  //   program: 'Ngữ pháp',
  //   description: 'Học theo cấp độ',
  //   available: false,
  // },
  {
    id: PROGRAM_IDS.NGHE,
    name: 'Văn Đức sensei',
    sex: 'M',
    date: '05/03/2020',
    startTime: '9:00 AM',
    endTime: '10:00 AM',
    tags: ['N5', 'N4', 'N3', 'N2', 'N1'],
    avatar: 'https://nihong0.herokuapp.com/avatars/logo.jpg',
    program: 'Luyện nghe',
    description: 'Học theo cấp độ',
    available: true,
  },
  {
    id: PROGRAM_IDS.HOITHOAI,
    name: 'Văn Đức sensei',
    sex: 'M',
    date: '05/03/2020',
    startTime: '9:00 AM',
    endTime: '10:00 AM',
    tags: ['N5', 'N4', 'N3', 'N2', 'N1'],
    avatar: 'https://nihong0.herokuapp.com/avatars/logo.jpg',
    program: 'Luyện hội thoại',
    description: 'Học theo cấp độ',
    available: true,
  },
  // {
  //   id: PROGRAM_IDS.THI,
  //   name: 'Văn Đức sensei',
  //   sex: 'M',
  //   date: '05/03/2020',
  //   startTime: '11:00 AM',
  //   endTime: '12:00 AM',
  //   tags: ['N5', 'N4', 'N3', 'N2', 'N1'],
  //   avatar: 'https://nihong0.herokuapp.com/avatars/logo.jpg',
  //   program: 'Luyện thi',
  //   description: 'Học theo cấp độ',
  //   available: false,
  // },
];
